name: Auto Merge Codex PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GH_TOKEN: ${{ secrets.YOUR_PAT }}
